source_url: https://xkcd.com

db:
  db_file: database.json
  indexPath: index.json

parallel: 42 # =~NumCPU*3.5

log: debug

server:
  addr: localhost:4444
  readTimeout: 10s
  writeTimeout: 10s

refreshInterval: 1m