source_url: https://xkcd.com

db:
  addr: 127.0.0.1:5555
  username: developer
  password: developer
  db: comics
  sslmode: disable
  maxConns: 10
  reload: false
  version: 2

apiConcurrency: 192

rateLimit: 
  limit: 30
  burst: 5

parallel: 42 # =~NumCPU*3.5

log: debug

server:
  addr: localhost:4444
  readTimeout: 10s
  writeTimeout: 10s

refreshTime: 23:16:00 +0300

auth:
  secret: secret
  token_max_time: 24h