### valid request, admin token
POST http://localhost:4444/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTcwNDYzNjcsInJvbGUiOiJhZG1pbiJ9.d7C8U-n5aTQtFxsZ2gVpnrW005P1HlxFCJ3ojaTkvFw

{}

### invalid request, user token
POST http://localhost:4444/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTYyMTg5MzYsInJvbGUiOiJ1c2VyIn0.74QlqTd-wuvxCz6rofjuqYuiaYPWKp5bkRS_op3xFxE

### user token
GET http://localhost:4444/pics?search="I'll follow your questions"
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTcwNDYzNjcsInJvbGUiOiJhZG1pbiJ9.d7C8U-n5aTQtFxsZ2gVpnrW005P1HlxFCJ3ojaTkvFw

### admin token
GET http://localhost:4444/pics?search="apple doctor"
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTY3MTI3MDIsInJvbGUiOiJ1c2VyIn0.6e0oUbSrj2he3fZPwts4mh9Z3OfFeMNIkgJHLmcuQRg


###
POST http://localhost:4444/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

// admin password: admin
// user1 password: 123456
// user2 password: 1234